version: "3.9"
services:
  ytdct:
    image: marschal66/ytdiscordtogether:v0.3.0
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - ytdct
  pocketbase:
    image: augustodelg/pocketbase:latest
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - pocketbase-data:/pb_data
    networks:
      - ytdct
volumes:
  pocketbase-data:
networks:
  ytdct:
