version: "3.9"
services:
  ytdct:
    image: marschal66/ytdiscordtogether:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - ytdct
  pocketbase:
    image: augustodelg/pocketbase:latest
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - type: bind
        source: ./pocketbase/
        target: /pocketbase/
    networks:
      - ytdct
volumes:
  pocketbase-data:
networks:
  ytdct:
