version: "3.9"
services:
  ytdct:
    image: marschal66/ytdiscordtogether:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - ytdct
  pocketbase:
    image: spectado/pocketbase
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./pocketbase/pb_data
        target: /pb_data
      - type: bind
        source: ./pocketbase/pb_migration
        target: /pb_migration
    networks:
      - ytdct
volumes:
  pocketbase-data:
  pocketbase-migration:
networks:
  ytdct:
