version: "3.9"
services:
  ytdct:
    image: marschal66/ytdiscordtogether:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - ytdct
  pocketbase:
    image: spectado/pocketbase
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./pocketbase/
        target: /pb_data
    networks:
      - ytdct
volumes:
  pocketbase-data:
networks:
  ytdct:
