name: Youtube Discord Together - dev
run-name: ${{ github.actor }} started this workflow
on:
  push:
    branches:
      - dev
jobs:
  Release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: build
        run: npm run build
      - name: create tags
        id: tagger
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tagger.outputs.new_tag }}
          release_name: Release ${{ steps.tagger.outputs.new_tag }}
          body: |
            Changes in this Release
            - ${{ github.event.head_commit.message }}
          # link to changelog
          draft: false
          prerelease: false
  Docker:
    runs-on: ubuntu-latest
    needs: [Release]
    steps:
      - uses: actions/checkout@v2
      - run: echo $GITHUB_SHA
      - name: Build the Docker image
        run: |
          docker logout
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
          docker build . --file Dockerfile --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/ytdiscordtogether:${{ steps.tagger.outputs.new_tag }}
          docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/ytdiscordtogether:${{ steps.tagger.outputs.new_tag }}
  Webhook:
    runs-on: ubuntu-latest
    needs: [Release, Docker]
    steps:
      - name: Send Webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: https://webhook.site/2a3024bc-adf7-4fc6-b224-63a4dce21ed6
          WEBHOOK_MESSAGE: "New Release: ${{ steps.tagger.outputs.new_tag }}"
