name: Youtube Discord Together - Release and Docker Process
run-name: ${{ github.actor }} started a release and docker process
on: [push]
jobs:
  Build-Release-Process:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: build
        run: npm run build
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
<<<<<<< HEAD
          tag_name: ${{ github.ref }}
=======
          tag_name: ${{ github.run_id }}
>>>>>>> 7fe4303 (changed tag_name to github.run_id)
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
  Docker-Process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run:
          echo $GITHUB_SHA
      - name: Build the Docker image
        run: |
          docker logout
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
          docker build . --file Dockerfile --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/ytdiscordtogether:12345
          docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/ytdiscordtogether:12345
