name: Youtube Discord Together - Release and Docker Process
run-name: ${{ github.actor }} started a release and docker process
on: [push]
#TODO: Add a TAG control process
jobs:
  Build-Release-Process:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: build
        run: npm run build
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }} #TODO: Set to a tag of format "[0-9]+.[0-9]+.[0-9]+"
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - ${{ github.event.head_commit.message }}
          # link to changelog
          draft: false
          prerelease: false
  Docker-Process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        #TODO: Set to a tag of format "[0-9]+.[0-9]+.[0-9]+"
        run: |
          docker logout
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
          docker build . --file Dockerfile --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/ytdiscordtogether:${{ github.run_id }}
          docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/ytdiscordtogether:${{ github.run_id }}
